<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Invoice <?php echo e($invoice->invoice_number); ?></title>
  <style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #10223e; }
    .header { margin-bottom: 18px; }
    .title { margin: 0 0 6px; font-size: 22px; color: #0f2748; }
    .meta { margin: 0; color: #4a617f; line-height: 1.5; }
    .grid { width: 100%; border-collapse: collapse; margin-top: 12px; }
    .grid th, .grid td { border: 1px solid #d9e2ef; padding: 8px; text-align: left; vertical-align: top; }
    .grid th { background: #f3f7fd; color: #223f64; width: 28%; }
    .summary { width: 46%; margin-left: auto; border-collapse: collapse; margin-top: 14px; }
    .summary td { border: 1px solid #d9e2ef; padding: 8px; }
    .summary .label { background: #f3f7fd; color: #223f64; width: 55%; }
    .summary .value { text-align: right; font-weight: 600; }
    .summary .total .label,
    .summary .total .value { font-weight: 700; font-size: 13px; background: #eef4fc; }
    .status { display: inline-block; border: 1px solid #d1d9e6; border-radius: 999px; padding: 3px 10px; text-transform: uppercase; font-size: 10px; letter-spacing: .05em; }
    .note { margin-top: 14px; color: #2a3f5f; white-space: pre-wrap; }
    .foot { margin-top: 24px; color: #6a7f9f; font-size: 11px; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">Invoice <?php echo e($invoice->invoice_number); ?></h1>
    <p class="meta"><strong>Issued:</strong> <?php echo e($invoice->issued_at?->format('Y-m-d') ?: '-'); ?></p>
    <p class="meta"><strong>Due date:</strong> <?php echo e($invoice->due_date?->format('Y-m-d') ?: '-'); ?></p>
    <p class="meta"><strong>Status:</strong> <span class="status"><?php echo e($invoice->status); ?></span></p>
  </div>

  <table class="grid">
    <tr>
      <th>Bill To</th>
      <td>
        <?php echo e($client?->name ?: 'Client'); ?><br>
        <?php echo e($client?->email ?: '-'); ?><br>
        <?php echo e($client?->phone ?: '-'); ?>

      </td>
    </tr>
    <tr>
      <th>Project</th>
      <td>
        <?php echo e($project?->title ?: '-'); ?><br>
        <?php echo e($project?->service_type ?: ''); ?><?php echo e($project?->property_address ? ' - ' . $project->property_address : ''); ?>

      </td>
    </tr>
    <tr>
      <th>Currency</th>
      <td><?php echo e(strtoupper((string) $invoice->currency)); ?></td>
    </tr>
  </table>

  <table class="summary">
    <tr>
      <td class="label">Subtotal</td>
      <td class="value"><?php echo e(number_format((float) $subtotal, 2)); ?> <?php echo e(strtoupper((string) $invoice->currency)); ?></td>
    </tr>
    <?php if($includeTax): ?>
    <tr>
      <td class="label">Tax (<?php echo e(number_format((float) $taxRate, 2)); ?>%)</td>
      <td class="value"><?php echo e(number_format((float) $taxAmount, 2)); ?> <?php echo e(strtoupper((string) $invoice->currency)); ?></td>
    </tr>
    <?php endif; ?>
    <tr class="total">
      <td class="label">Total</td>
      <td class="value"><?php echo e(number_format((float) $total, 2)); ?> <?php echo e(strtoupper((string) $invoice->currency)); ?></td>
    </tr>
  </table>

  <?php if(!blank($invoice->notes)): ?>
    <div class="note"><strong>Notes:</strong><br><?php echo e($invoice->notes); ?></div>
  <?php endif; ?>

  <p class="foot">Generated by Maccento Client Portal on <?php echo e(now()->format('Y-m-d H:i:s')); ?>.</p>
</body>
</html>
<?php /**PATH /home/asifk/projects/maccento/resources/views/user/pdf/invoice.blade.php ENDPATH**/ ?>