<?php

namespace App\Jobs;

use App\Mail\BrandedNotificationMail;
use App\Models\LeadProfile;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Mail;

class SendLeadNotificationJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function __construct(private readonly int $leadProfileId)
    {
    }

    public function handle(): void
    {
        $leadProfile = LeadProfile::find($this->leadProfileId);
        if (!$leadProfile) {
            return;
        }

        $recipient = (string) config('mail.lead_alert_address');
        if ($recipient === '') {
            return;
        }

        $subject = sprintf('Qualified Lead #%d', $leadProfile->id);
        $body = sprintf(
            "Lead qualified.\nName: %s\nEmail: %s\nPhone: %s\nService: %s\nLocation: %s\nTimeline: %s\nScore: %d",
            $leadProfile->name ?? '-',
            $leadProfile->email ?? '-',
            $leadProfile->phone ?? '-',
            $leadProfile->service_type ?? '-',
            $leadProfile->location ?? '-',
            $leadProfile->timeline ?? '-',
            $leadProfile->score ?? 0,
        );

        Mail::to($recipient)->send(new BrandedNotificationMail(
            subjectLine: $subject,
            heading: 'Qualified Lead Alert',
            bodyLines: $this->bodyToLines($body),
            intro: 'A lead has been automatically qualified and requires your review.',
            ctaLabel: 'Open CRM Dashboard',
            ctaUrl: route('admin.dashboard'),
            footerNote: 'Generated by Maccento CRM lead qualification pipeline.',
        ));
    }

    /**
     * @return array<int,string>
     */
    private function bodyToLines(string $body): array
    {
        return collect(preg_split('/\r\n|\r|\n/', $body) ?: [])
            ->map(static fn (string $line): string => trim($line))
            ->filter(static fn (string $line): bool => $line !== '')
            ->values()
            ->all();
    }
}
